#!/usr/bin/env node
/**
 * Validates the ticket files in docs/backlog/ and regenerates docs/backlog/INDEX.md.
 *
 *   node scripts/backlog.mjs           regenerate INDEX.md
 *   node scripts/backlog.mjs --check   validate only, and fail if INDEX.md is stale
 *
 * `--check` runs in `npm run verify` and in CI, so a malformed ticket or a
 * forgotten index refresh fails like any other broken build. Plain Node, no
 * dependencies — the backlog must not rot because a package went stale.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BACKLOG = join(ROOT, 'docs', 'backlog');
const INDEX = join(BACKLOG, 'INDEX.md');
const RESERVED = new Set(['README.md', 'TEMPLATE.md', 'INDEX.md']);

const STATUSES = ['open', 'in-progress', 'blocked', 'done'];
const PRIORITIES = ['P0', 'P1', 'P2', 'P3'];
const TYPES = ['bug', 'security', 'refactor', 'feature', 'chore', 'docs'];
const REQUIRED = ['id', 'title', 'status', 'priority', 'type'];

const errors = [];

function parseFrontmatter(file, source) {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    errors.push(`${file}: missing YAML frontmatter block`);
    return null;
  }
  const fields = {};
  for (const line of match[1].split(/\r?\n/)) {
    if (!line.trim() || line.trimStart().startsWith('#')) continue;
    const sep = line.indexOf(':');
    if (sep === -1) {
      errors.push(`${file}: cannot parse frontmatter line: ${line}`);
      continue;
    }
    fields[line.slice(0, sep).trim()] = line
      .slice(sep + 1)
      .trim()
      .replace(/^["']|["']$/g, '');
  }
  return fields;
}

function loadTickets() {
  const files = readdirSync(BACKLOG)
    .filter((f) => f.endsWith('.md') && !RESERVED.has(f))
    .sort();

  const tickets = [];
  const seenIds = new Map();

  for (const file of files) {
    const fields = parseFrontmatter(file, readFileSync(join(BACKLOG, file), 'utf8'));
    if (!fields) continue;

    for (const key of REQUIRED) {
      if (!fields[key]) errors.push(`${file}: missing required field "${key}"`);
    }
    if (fields.status && !STATUSES.includes(fields.status)) {
      errors.push(`${file}: status "${fields.status}" not one of ${STATUSES.join(', ')}`);
    }
    if (fields.priority && !PRIORITIES.includes(fields.priority)) {
      errors.push(`${file}: priority "${fields.priority}" not one of ${PRIORITIES.join(', ')}`);
    }
    if (fields.type && !TYPES.includes(fields.type)) {
      errors.push(`${file}: type "${fields.type}" not one of ${TYPES.join(', ')}`);
    }
    // The filename carries the id so a ticket can be found without opening it.
    if (fields.id && !file.startsWith(`${fields.id}-`)) {
      errors.push(`${file}: filename must start with the id "${fields.id}-"`);
    }
    if (fields.id) {
      if (seenIds.has(fields.id)) {
        errors.push(`${file}: duplicate id "${fields.id}", already used by ${seenIds.get(fields.id)}`);
      }
      seenIds.set(fields.id, file);
    }

    tickets.push({ ...fields, file });
  }

  return tickets;
}

function renderIndex(tickets) {
  const byPriority = (a, b) =>
    PRIORITIES.indexOf(a.priority) - PRIORITIES.indexOf(b.priority) || a.id.localeCompare(b.id);

  const lines = [
    '# Backlog',
    '',
    '<!-- Generated by scripts/backlog.mjs. Do not edit by hand: edit the ticket',
    '     files and run `npm run backlog`. -->',
    '',
  ];

  const open = tickets.filter((t) => t.status !== 'done');
  const done = tickets.filter((t) => t.status === 'done');

  const counts = PRIORITIES.map((p) => `${p}: ${open.filter((t) => t.priority === p).length}`);
  lines.push(`${open.length} open · ${done.length} done · ${counts.join(' · ')}`, '');

  for (const status of STATUSES.filter((s) => s !== 'done')) {
    const group = tickets.filter((t) => t.status === status).sort(byPriority);
    if (!group.length) continue;
    lines.push(`## ${status}`, '');
    lines.push('| Pri | Type | Ticket |', '| --- | --- | --- |');
    for (const t of group) {
      lines.push(`| ${t.priority} | ${t.type} | [${t.id} — ${t.title}](${t.file}) |`);
    }
    lines.push('');
  }

  if (done.length) {
    lines.push('## done', '');
    for (const t of done.sort(byPriority)) {
      lines.push(`- ~~[${t.id} — ${t.title}](${t.file})~~`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

const tickets = loadTickets();
const rendered = renderIndex(tickets);
const checkOnly = process.argv.includes('--check');

if (errors.length) {
  console.error('Backlog validation failed:\n');
  for (const e of errors) console.error(`  - ${e}`);
  console.error('\nTicket format: docs/backlog/TEMPLATE.md');
  process.exit(1);
}

if (checkOnly) {
  let current = '';
  try {
    current = readFileSync(INDEX, 'utf8');
  } catch {
    // Missing index is the same failure as a stale one.
  }
  if (current !== rendered) {
    console.error('docs/backlog/INDEX.md is out of date. Run `npm run backlog` and commit it.');
    process.exit(1);
  }
  console.log(`Backlog OK: ${tickets.length} tickets, index up to date.`);
} else {
  writeFileSync(INDEX, rendered);
  console.log(`Wrote docs/backlog/INDEX.md (${tickets.length} tickets).`);
}
